# Generated by Django 4.1.3 on 2022-11-07 23:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', ckeditor.fields.RichTextField(null=True)),
                ('emisor', models.CharField(max_length=30)),
                ('receptor', models.CharField(max_length=30)),
            ],
        ),
    ]
